version: '3.8'

services:
  new-app:
    build:
      context: .
      target: development
    ports:
      - "3031:3031"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=dev
    stdin_open: true
    tty: true
    command: yarn dev
    depends_on:
      - mongodb_db
      - elasticsearch 
    networks:
      - livestream-ecommerce-network

  mongodb_db:
    image: mongo:8.0
    networks:
      - livestream-ecommerce-network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - livestream-ecommerce-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} 
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - livestream-ecommerce-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD} 
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - livestream-ecommerce-network

networks:
  livestream-ecommerce-network:
    driver: bridge

volumes:
  mongo_data:
  es_data: 