version: '3.8'

services:
  new-app:
    # build: 
    #   context: .
    #   target: development
    image: livestream-ecommerce-api-new-app:latest
    ports:
      - "3031:3031"
    env_file:
      - .env
    volumes:
      - .:/app            # Đồng bộ code từ máy vào Docker để nodemon chạy
      - /app/node_modules
    depends_on:
      - mongodb_db
    networks:
      - livestream-ecommerce-network

  mongodb_db:
    image: mongo:6.0 
    networks:
      - livestream-ecommerce-network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - livestream-ecommerce-network

networks:
  livestream-ecommerce-network:
    driver: bridge

volumes:
  mongo_data: